FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /react-crud
RUN apt-get update

COPY requirements.txt /react-crud/

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . /react-crud/

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]