# Generated by Django 5.2 on 2025-05-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_alter_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.IntegerField(blank=True, choices=[(1, 'Admin'), (2, 'User')], default=2, null=True),
        ),
    ]
