# Generated by Django 5.2 on 2025-05-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0004_user_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_otp_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
