# Generated by Django 5.2 on 2025-05-28 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0005_user_is_email_otp_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='user',
            table='tbl_user',
        ),
    ]
